export const events = [
    {
      slug: "codestorm-5-0",
      name: "CodeStorm 5.0",
      eventType: "Hackathon",
      eventDate: "2025-06-15",
      eventLocation: "Bangalore, Karnataka",
      collegeName: "RV College of Engineering",
      registrationCount: 350,
      registrationDeadline: "2025-06-10",
      description:
        "A 36-hour national-level hackathon focusing on AI and sustainability challenges.",
      contactEmail: "codestorm@rvce.edu.in",
      eventLink: "https://codestorm.rvce.edu.in",
    },
    {
      slug: "nextgen-founders-meetup",
      name: "NextGen Founders Meetup",
      eventType: "Startup",
      eventDate: "2025-07-05",
      eventLocation: "Hyderabad, Telangana",
      collegeName: "IIIT Hyderabad",
      registrationCount: 180,
      registrationDeadline: "2025-06-25",
      description:
        "A networking and pitching event for early-stage startup founders and student entrepreneurs.",
      contactEmail: "startups@iiit.ac.in",
      eventLink: "https://iiit.ac.in/startups-meetup",
    },
    {
      slug: "ai-in-medicine-future-talk",
      name: "AI in Medicine - Future Talk",
      eventType: "Tech Talk",
      eventDate: "2025-05-30",
      eventLocation: "Mumbai, Maharashtra",
      collegeName: "IIT Bombay",
      registrationCount: 120,
      registrationDeadline: "2025-05-28",
      description:
        "A tech talk on the impact of Artificial Intelligence in the healthcare and pharmaceutical industry.",
      contactEmail: "talks@iitb.ac.in",
      eventLink: "https://iitb.ac.in/events/ai-medicine",
    },
    {
      slug: "innovate-india-challenge",
      name: "Innovate India Challenge",
      eventType: "Competition",
      eventDate: "2025-08-20",
      eventLocation: "Delhi",
      collegeName: "Delhi Technological University",
      registrationCount: 600,
      registrationDeadline: "2025-08-10",
      description:
        "National innovation competition for prototypes, business ideas, and tech-based solutions.",
      contactEmail: "innovate@dtu.ac.in",
      eventLink: "https://dtu.ac.in/innovate-india",
    },
    {
      slug: "mentorverse-2025",
      name: "MentorVerse 2025",
      eventType: "Mentorship Session",
      eventDate: "2025-06-12",
      eventLocation: "Chennai, Tamil Nadu",
      collegeName: "SRM Institute of Science and Technology",
      registrationCount: 90,
      registrationDeadline: "2025-06-05",
      description:
        "Exclusive one-on-one mentorship sessions with industry leaders across tech, finance, and design.",
      contactEmail: "mentorverse@srmist.edu.in",
      eventLink: "https://srmist.edu.in/mentorverse",
    },
    {
      slug: "cultura-2025",
      name: "Cultura 2025",
      eventType: "Cultural Event",
      eventDate: "2025-09-01",
      eventLocation: "Pune, Maharashtra",
      collegeName: "MIT World Peace University",
      registrationCount: 1500,
      registrationDeadline: "2025-08-20",
      description:
        "Annual cultural extravaganza featuring dance, music, fashion shows, and more.",
      contactEmail: "cultura@mitwpu.edu.in",
      eventLink: "https://mitwpu.edu.in/cultura2025",
    },
  ];
  